name: agenda_boa_test
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.2.2
  firebase_core: ^1.3.0
  observable_ish: ^3.0.0
  stacked: ^2.1.7
  stacked_services: ^0.8.6

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.6

flutter:
  uses-material-design: true